
export const APPWRITE_PROJECT_ID = process.env.APPWRITE_PROJECT_ID!
export const APPWRITE_DATABASE_ID = process.env.APPWRITE_DATABASE_ID!
export const APPWRITE_TODOS_COLLECTION_ID= process.env.APPWRITE_TODOS_COLLECTION_ID!